#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BASEDEDATOSPRUEBAS")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertClientes(Clientes instance);
    partial void UpdateClientes(Clientes instance);
    partial void DeleteClientes(Clientes instance);
    partial void InsertLocalidades(Localidades instance);
    partial void UpdateLocalidades(Localidades instance);
    partial void DeleteLocalidades(Localidades instance);
    partial void InsertProvincias(Provincias instance);
    partial void UpdateProvincias(Provincias instance);
    partial void DeleteProvincias(Provincias instance);
    partial void InsertDepartamentos(Departamentos instance);
    partial void UpdateDepartamentos(Departamentos instance);
    partial void DeleteDepartamentos(Departamentos instance);
    #endregion
		
		public dbDataContext() : 
				base(global::Model.Properties.Settings.Default.BASEDEDATOSPRUEBASConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clientes> Clientes
		{
			get
			{
				return this.GetTable<Clientes>();
			}
		}
		
		public System.Data.Linq.Table<Localidades> Localidades
		{
			get
			{
				return this.GetTable<Localidades>();
			}
		}
		
		public System.Data.Linq.Table<Provincias> Provincias
		{
			get
			{
				return this.GetTable<Provincias>();
			}
		}
		
		public System.Data.Linq.Table<Departamentos> Departamentos
		{
			get
			{
				return this.GetTable<Departamentos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarPresupuestos")]
		public ISingleResult<listarPresupuestosResult> listarPresupuestos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarPresupuestosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerCalculosAuxiliares")]
		public ISingleResult<obtenerCalculosAuxiliaresResult> obtenerCalculosAuxiliares([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPresupuesto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPresupuesto);
			return ((ISingleResult<obtenerCalculosAuxiliaresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarCliente")]
		public int modificarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> cuit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RazonSocial", DbType="VarChar(100)")] string razonSocial, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Domicilio", DbType="VarChar(150)")] string domicilio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string tel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string cel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idLocalidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuit, razonSocial, domicilio, tel, cel, email, idLocalidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarClientesEliminados")]
		public ISingleResult<ListarClientesEliminadosResult> ListarClientesEliminados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarClientesEliminadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCliente")]
		public int InsertarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> cuit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string tel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string cel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string razonSocial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idLocalidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuit, tel, cel, email, direccion, razonSocial, idLocalidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ExisteCuit")]
		public ISingleResult<ExisteCuitResult> ExisteCuit([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> cuit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuit);
			return ((ISingleResult<ExisteCuitResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarCliente")]
		public int EliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> cuit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuit);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RecuperarCLiente")]
		public int RecuperarCLiente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> cuit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuit);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarLocalidad")]
		public int agregarLocalidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartamento, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarLocalidad")]
		public int modificarLocalidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idLocalidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idLocalidad, idDepartamento, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarLocalidades")]
		public ISingleResult<listarLocalidadesResult> listarLocalidades([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartamento);
			return ((ISingleResult<listarLocalidadesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarDepartamento")]
		public int agregarDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProvincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProvincia, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarDepartamento")]
		public ISingleResult<listarDepartamentoResult> listarDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProvincia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProvincia);
			return ((ISingleResult<listarDepartamentoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarDepartamento")]
		public int modificarDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProvincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProvincia, idDepartamento, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarProvincia")]
		public int agregarProvincia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarProvincias")]
		public ISingleResult<listarProvinciasResult> listarProvincias()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarProvinciasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarProvincia")]
		public int modificarProvincia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProvincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProvincia, nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarClienteActivos")]
		public ISingleResult<ListarClienteActivosResult> ListarClienteActivos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarClienteActivosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarIDDepartamento")]
		public ISingleResult<buscarIDDepartamentoResult> buscarIDDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idLocalidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idLocalidad);
			return ((ISingleResult<buscarIDDepartamentoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarIDProvincia")]
		public ISingleResult<buscarIDProvinciaResult> buscarIDProvincia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartamento);
			return ((ISingleResult<buscarIDProvinciaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarClienteDefinitivo")]
		public int eliminarClienteDefinitivo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> cuit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuit);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cliente")]
	public partial class Clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Cuit;
		
		private string _RazonSocial;
		
		private string _Domicilio;
		
		private string _Tel;
		
		private string _Cel;
		
		private string _Email;
		
		private int _IdLocalidad;
		
		private int _Estado;
		
		private EntityRef<Localidades> _Localidades;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCuitChanging(long value);
    partial void OnCuitChanged();
    partial void OnRazonSocialChanging(string value);
    partial void OnRazonSocialChanged();
    partial void OnDomicilioChanging(string value);
    partial void OnDomicilioChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnCelChanging(string value);
    partial void OnCelChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnIdLocalidadChanging(int value);
    partial void OnIdLocalidadChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Clientes()
		{
			this._Localidades = default(EntityRef<Localidades>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuit", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Cuit
		{
			get
			{
				return this._Cuit;
			}
			set
			{
				if ((this._Cuit != value))
				{
					this.OnCuitChanging(value);
					this.SendPropertyChanging();
					this._Cuit = value;
					this.SendPropertyChanged("Cuit");
					this.OnCuitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this.OnRazonSocialChanging(value);
					this.SendPropertyChanging();
					this._RazonSocial = value;
					this.SendPropertyChanged("RazonSocial");
					this.OnRazonSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio", DbType="VarChar(150)")]
		public string Domicilio
		{
			get
			{
				return this._Domicilio;
			}
			set
			{
				if ((this._Domicilio != value))
				{
					this.OnDomicilioChanging(value);
					this.SendPropertyChanging();
					this._Domicilio = value;
					this.SendPropertyChanged("Domicilio");
					this.OnDomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(100)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cel", DbType="VarChar(100)")]
		public string Cel
		{
			get
			{
				return this._Cel;
			}
			set
			{
				if ((this._Cel != value))
				{
					this.OnCelChanging(value);
					this.SendPropertyChanging();
					this._Cel = value;
					this.SendPropertyChanged("Cel");
					this.OnCelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLocalidad", DbType="Int NOT NULL")]
		public int IdLocalidad
		{
			get
			{
				return this._IdLocalidad;
			}
			set
			{
				if ((this._IdLocalidad != value))
				{
					if (this._Localidades.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLocalidadChanging(value);
					this.SendPropertyChanging();
					this._IdLocalidad = value;
					this.SendPropertyChanged("IdLocalidad");
					this.OnIdLocalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="localidad_cliente", Storage="_Localidades", ThisKey="IdLocalidad", OtherKey="Id", IsForeignKey=true)]
		public Localidades Localidades
		{
			get
			{
				return this._Localidades.Entity;
			}
			set
			{
				Localidades previousValue = this._Localidades.Entity;
				if (((previousValue != value) 
							|| (this._Localidades.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Localidades.Entity = null;
						previousValue.Clientes.Remove(this);
					}
					this._Localidades.Entity = value;
					if ((value != null))
					{
						value.Clientes.Add(this);
						this._IdLocalidad = value.Id;
					}
					else
					{
						this._IdLocalidad = default(int);
					}
					this.SendPropertyChanged("Localidades");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.localidad")]
	public partial class Localidades : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _idDepartamento;
		
		private string _Nombre;
		
		private EntitySet<Clientes> _Clientes;
		
		private EntityRef<Departamentos> _Departamentos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Localidades()
		{
			this._Clientes = new EntitySet<Clientes>(new Action<Clientes>(this.attach_Clientes), new Action<Clientes>(this.detach_Clientes));
			this._Departamentos = default(EntityRef<Departamentos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					if (this._Departamentos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="localidad_cliente", Storage="_Clientes", ThisKey="Id", OtherKey="IdLocalidad")]
		public EntitySet<Clientes> Clientes
		{
			get
			{
				return this._Clientes;
			}
			set
			{
				this._Clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="departamento_localidad", Storage="_Departamentos", ThisKey="idDepartamento", OtherKey="ID", IsForeignKey=true)]
		public Departamentos Departamentos
		{
			get
			{
				return this._Departamentos.Entity;
			}
			set
			{
				Departamentos previousValue = this._Departamentos.Entity;
				if (((previousValue != value) 
							|| (this._Departamentos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamentos.Entity = null;
						previousValue.Localidades.Remove(this);
					}
					this._Departamentos.Entity = value;
					if ((value != null))
					{
						value.Localidades.Add(this);
						this._idDepartamento = value.ID;
					}
					else
					{
						this._idDepartamento = default(int);
					}
					this.SendPropertyChanged("Departamentos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Clientes(Clientes entity)
		{
			this.SendPropertyChanging();
			entity.Localidades = this;
		}
		
		private void detach_Clientes(Clientes entity)
		{
			this.SendPropertyChanging();
			entity.Localidades = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.provincia")]
	public partial class Provincias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nombre;
		
		private int _IdPais;
		
		private EntitySet<Departamentos> _Departamentos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdPaisChanging(int value);
    partial void OnIdPaisChanged();
    #endregion
		
		public Provincias()
		{
			this._Departamentos = new EntitySet<Departamentos>(new Action<Departamentos>(this.attach_Departamentos), new Action<Departamentos>(this.detach_Departamentos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPais", DbType="Int NOT NULL")]
		public int IdPais
		{
			get
			{
				return this._IdPais;
			}
			set
			{
				if ((this._IdPais != value))
				{
					this.OnIdPaisChanging(value);
					this.SendPropertyChanging();
					this._IdPais = value;
					this.SendPropertyChanged("IdPais");
					this.OnIdPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="provincia_departamento", Storage="_Departamentos", ThisKey="ID", OtherKey="idProvincia")]
		public EntitySet<Departamentos> Departamentos
		{
			get
			{
				return this._Departamentos;
			}
			set
			{
				this._Departamentos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Departamentos(Departamentos entity)
		{
			this.SendPropertyChanging();
			entity.Provincias = this;
		}
		
		private void detach_Departamentos(Departamentos entity)
		{
			this.SendPropertyChanging();
			entity.Provincias = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.departamento")]
	public partial class Departamentos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _idProvincia;
		
		private string _Nombre;
		
		private EntitySet<Localidades> _Localidades;
		
		private EntityRef<Provincias> _Provincias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnidProvinciaChanging(int value);
    partial void OnidProvinciaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Departamentos()
		{
			this._Localidades = new EntitySet<Localidades>(new Action<Localidades>(this.attach_Localidades), new Action<Localidades>(this.detach_Localidades));
			this._Provincias = default(EntityRef<Provincias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProvincia", DbType="Int NOT NULL")]
		public int idProvincia
		{
			get
			{
				return this._idProvincia;
			}
			set
			{
				if ((this._idProvincia != value))
				{
					if (this._Provincias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProvinciaChanging(value);
					this.SendPropertyChanging();
					this._idProvincia = value;
					this.SendPropertyChanged("idProvincia");
					this.OnidProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="departamento_localidad", Storage="_Localidades", ThisKey="ID", OtherKey="idDepartamento")]
		public EntitySet<Localidades> Localidades
		{
			get
			{
				return this._Localidades;
			}
			set
			{
				this._Localidades.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="provincia_departamento", Storage="_Provincias", ThisKey="idProvincia", OtherKey="ID", IsForeignKey=true)]
		public Provincias Provincias
		{
			get
			{
				return this._Provincias.Entity;
			}
			set
			{
				Provincias previousValue = this._Provincias.Entity;
				if (((previousValue != value) 
							|| (this._Provincias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Provincias.Entity = null;
						previousValue.Departamentos.Remove(this);
					}
					this._Provincias.Entity = value;
					if ((value != null))
					{
						value.Departamentos.Add(this);
						this._idProvincia = value.ID;
					}
					else
					{
						this._idProvincia = default(int);
					}
					this.SendPropertyChanged("Provincias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Localidades(Localidades entity)
		{
			this.SendPropertyChanging();
			entity.Departamentos = this;
		}
		
		private void detach_Localidades(Localidades entity)
		{
			this.SendPropertyChanging();
			entity.Departamentos = null;
		}
	}
	
	public partial class listarPresupuestosResult
	{
		
		private int _Número_de_presupuesto;
		
		private System.DateTime _Fecha;
		
		private System.DateTime _Vencimiento;
		
		private string _Cliente;
		
		private string _Paciente;
		
		private string _Medico;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _Fecha_de_cirugía;
		
		private System.Nullable<System.DateTime> _Fecha_de_Autorización;
		
		private System.Nullable<bool> _consumoTiene;
		
		public listarPresupuestosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Número de presupuesto]", Storage="_Número_de_presupuesto", DbType="Int NOT NULL")]
		public int Número_de_presupuesto
		{
			get
			{
				return this._Número_de_presupuesto;
			}
			set
			{
				if ((this._Número_de_presupuesto != value))
				{
					this._Número_de_presupuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vencimiento", DbType="Date NOT NULL")]
		public System.DateTime Vencimiento
		{
			get
			{
				return this._Vencimiento;
			}
			set
			{
				if ((this._Vencimiento != value))
				{
					this._Vencimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Paciente
		{
			get
			{
				return this._Paciente;
			}
			set
			{
				if ((this._Paciente != value))
				{
					this._Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medico", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Medico
		{
			get
			{
				return this._Medico;
			}
			set
			{
				if ((this._Medico != value))
				{
					this._Medico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de cirugía]", Storage="_Fecha_de_cirugía", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_de_cirugía
		{
			get
			{
				return this._Fecha_de_cirugía;
			}
			set
			{
				if ((this._Fecha_de_cirugía != value))
				{
					this._Fecha_de_cirugía = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Autorización]", Storage="_Fecha_de_Autorización", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_de_Autorización
		{
			get
			{
				return this._Fecha_de_Autorización;
			}
			set
			{
				if ((this._Fecha_de_Autorización != value))
				{
					this._Fecha_de_Autorización = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consumoTiene", DbType="Bit")]
		public System.Nullable<bool> consumoTiene
		{
			get
			{
				return this._consumoTiene;
			}
			set
			{
				if ((this._consumoTiene != value))
				{
					this._consumoTiene = value;
				}
			}
		}
	}
	
	public partial class obtenerCalculosAuxiliaresResult
	{
		
		private System.Nullable<int> _IdPresupuesto;
		
		private int _Id;
		
		private System.Nullable<decimal> _PrecioCosto;
		
		private System.Nullable<decimal> _Honorario;
		
		private System.Nullable<decimal> _GastosVarios;
		
		private System.Nullable<decimal> _Ganancia;
		
		private System.Nullable<decimal> _Subtotal;
		
		private string _Comentario;
		
		private int _Estado;
		
		public obtenerCalculosAuxiliaresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPresupuesto", DbType="Int")]
		public System.Nullable<int> IdPresupuesto
		{
			get
			{
				return this._IdPresupuesto;
			}
			set
			{
				if ((this._IdPresupuesto != value))
				{
					this._IdPresupuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioCosto", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PrecioCosto
		{
			get
			{
				return this._PrecioCosto;
			}
			set
			{
				if ((this._PrecioCosto != value))
				{
					this._PrecioCosto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Honorario", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Honorario
		{
			get
			{
				return this._Honorario;
			}
			set
			{
				if ((this._Honorario != value))
				{
					this._Honorario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GastosVarios", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> GastosVarios
		{
			get
			{
				return this._GastosVarios;
			}
			set
			{
				if ((this._GastosVarios != value))
				{
					this._GastosVarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ganancia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Ganancia
		{
			get
			{
				return this._Ganancia;
			}
			set
			{
				if ((this._Ganancia != value))
				{
					this._Ganancia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this._Subtotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(250)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class ListarClientesEliminadosResult
	{
		
		private long _Cuit;
		
		private string _RazonSocial;
		
		private string _Domicilio;
		
		private string _Tel;
		
		private string _Cel;
		
		private string _Email;
		
		private int _IdLocalidad;
		
		private int _Estado;
		
		public ListarClientesEliminadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuit", DbType="BigInt NOT NULL")]
		public long Cuit
		{
			get
			{
				return this._Cuit;
			}
			set
			{
				if ((this._Cuit != value))
				{
					this._Cuit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this._RazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio", DbType="VarChar(150)")]
		public string Domicilio
		{
			get
			{
				return this._Domicilio;
			}
			set
			{
				if ((this._Domicilio != value))
				{
					this._Domicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(100)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cel", DbType="VarChar(100)")]
		public string Cel
		{
			get
			{
				return this._Cel;
			}
			set
			{
				if ((this._Cel != value))
				{
					this._Cel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLocalidad", DbType="Int NOT NULL")]
		public int IdLocalidad
		{
			get
			{
				return this._IdLocalidad;
			}
			set
			{
				if ((this._IdLocalidad != value))
				{
					this._IdLocalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class ExisteCuitResult
	{
		
		private string _RazonSocial;
		
		public ExisteCuitResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this._RazonSocial = value;
				}
			}
		}
	}
	
	public partial class listarLocalidadesResult
	{
		
		private int _Id;
		
		private int _idDepartamento;
		
		private string _Nombre;
		
		public listarLocalidadesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					this._idDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class listarDepartamentoResult
	{
		
		private int _ID;
		
		private int _idProvincia;
		
		private string _Nombre;
		
		public listarDepartamentoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProvincia", DbType="Int NOT NULL")]
		public int idProvincia
		{
			get
			{
				return this._idProvincia;
			}
			set
			{
				if ((this._idProvincia != value))
				{
					this._idProvincia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class listarProvinciasResult
	{
		
		private int _ID;
		
		private string _Nombre;
		
		private int _IdPais;
		
		public listarProvinciasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPais", DbType="Int NOT NULL")]
		public int IdPais
		{
			get
			{
				return this._IdPais;
			}
			set
			{
				if ((this._IdPais != value))
				{
					this._IdPais = value;
				}
			}
		}
	}
	
	public partial class ListarClienteActivosResult
	{
		
		private long _Cuit;
		
		private string _RazonSocial;
		
		private string _Domicilio;
		
		private string _Tel;
		
		private string _Cel;
		
		private string _Email;
		
		private int _IdLocalidad;
		
		private int _Estado;
		
		private int _Id;
		
		private int _idDepartamento;
		
		private string _Nombre;
		
		public ListarClienteActivosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuit", DbType="BigInt NOT NULL")]
		public long Cuit
		{
			get
			{
				return this._Cuit;
			}
			set
			{
				if ((this._Cuit != value))
				{
					this._Cuit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this._RazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio", DbType="VarChar(150)")]
		public string Domicilio
		{
			get
			{
				return this._Domicilio;
			}
			set
			{
				if ((this._Domicilio != value))
				{
					this._Domicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(100)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cel", DbType="VarChar(100)")]
		public string Cel
		{
			get
			{
				return this._Cel;
			}
			set
			{
				if ((this._Cel != value))
				{
					this._Cel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLocalidad", DbType="Int NOT NULL")]
		public int IdLocalidad
		{
			get
			{
				return this._IdLocalidad;
			}
			set
			{
				if ((this._IdLocalidad != value))
				{
					this._IdLocalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					this._idDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class buscarIDDepartamentoResult
	{
		
		private int _idDepartamento;
		
		public buscarIDDepartamentoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					this._idDepartamento = value;
				}
			}
		}
	}
	
	public partial class buscarIDProvinciaResult
	{
		
		private int _idProvincia;
		
		public buscarIDProvinciaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProvincia", DbType="Int NOT NULL")]
		public int idProvincia
		{
			get
			{
				return this._idProvincia;
			}
			set
			{
				if ((this._idProvincia != value))
				{
					this._idProvincia = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
